apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: bank-of-anthos
requires:
- configs:
  - accounts
  path: src/accounts/skaffold.yaml
- configs:
  - ledger
  path: src/ledger/skaffold.yaml
- configs:
  - frontend
  path: src/frontend/skaffold.yaml
- configs:
  - loadgenerator
  path: src/loadgenerator/skaffold.yaml
- configs:
  - accounts-db
  path: src/accounts/accounts-db/skaffold.yaml
- configs:
  - ledger-db
  path: src/ledger/ledger-db/skaffold.yaml
- configs:
  - aifrontend
  path: src/aifrontend/skaffold.yaml
- configs:
  - aiservices
  path: src/aiservices/skaffold.yaml   

deploy:
  tolerateFailuresUntilDeadline: true
