# kubernetes-manifests/aifrontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: aifrontend
spec:
  type: NodePort
  selector:
    app: aifrontend
  ports:
  - port: 80
    targetPort: 8080
    # For minikube testing, use a NodePort (or remove type for ClusterIP).
