apiVersion: v1
kind: Service
metadata:
  name: aifrontend
spec:
  selector:
    app: aifrontend
  type: LoadBalancer            # exposes externally:contentReference[oaicite:15]{index=15}
  ports:
    - name: http
      port: 80
      targetPort: 5005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aifrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aifrontend
  template:
    metadata:
      labels:
        app: aifrontend
    spec:
      containers:
      - name: aifrontend
        image: gcr.io/bank-of-anthos-470616/aifrontend:latest
        ports:
        - containerPort: 5005
        env:
        - name: USERSERVICE_URL
          value: "http://userservice:5000"
        - name: CONTACTS_URL
          value: "http://contacts:5000"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5005
          initialDelaySeconds: 5
          periodSeconds: 10
