# kubernetes-manifests/aifrontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aifrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aifrontend
  template:
    metadata:
      labels:
        app: aifrontend
    spec:
      containers:
      - name: aifrontend
        image: gcr.io/${PROJECT_ID}/bank-of-anthos-aifrontend:latest
        ports:
        - containerPort: 8080
        # (Optionally set environment variables here)
