apiVersion: v1
kind: Service
metadata:
  name: airuntime
  labels:
    application: bank-of-anthos
    environment: development
    team: frontend
    tier: web
spec:
  selector:
    app: airuntime
    application: bank-of-anthos
    environment: development
    team: frontend
    tier: web
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airuntime
  labels:
    application: bank-of-anthos
    environment: development
    team: frontend
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airuntime
      application: bank-of-anthos
      environment: development
      team: frontend
      tier: web
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: airuntime
        application: bank-of-anthos
        environment: development
        team: frontend
        tier: web
    spec:
      serviceAccountName: bank-of-anthos
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: airuntime
          image: gcr.io/bank-of-anthos-470616/airuntime:latest
          ports:
            - containerPort: 8001
          env:
            - name: PUB_KEY_PATH
              value: "/tmp/.ssh/publickey"
          envFrom:
            - configMapRef:
                name: environment-config
            - configMapRef:
                name: ai-service-api-config
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: 8001
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["all"]
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp/.ssh
              name: publickey
              readOnly: true
      volumes:
        - name: publickey
          secret:
            secretName: jwt-key
            items:
              - key: jwtRS256.key.pub
                path: publickey
