apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: aifrontend
build:
  artifacts:
    - image: gcr.io/bank-of-anthos-470616/aifrontend
      context: .
deploy:
  kubectl:
    manifests:
      - ../../kubernetes-manifests/aifrontend.yaml
      - ../../kubernetes-manifests/ai-service-api-config.yaml
